name: Test Morphia Upgrades

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  Upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: >
            [
              {
                "id": "snapshot-repository",
                "url": "https://oss.sonatype.org/content/repositories/snapshots/",
                "releases": {
                  "enabled": "true",
                  "updatePolicy": "always",
                  "checksumPolicy": "fail"
                },
                "snapshots": {
                  "enabled": "tre",
                  "updatePolicy": "always",
                  "checksumPolicy": "fail"
                }
              }
            ]
          output_file: .m2/settings.xml
      - name: Build with Tests
        run: |
          mvn -e -U org.openrewrite.maven:rewrite-maven-plugin:run \
            -Drewrite.recipeArtifactCoordinates=dev.morphia.morphia:rewrite:3.0.0-SNAPSHOT \
            -Drewrite.activeRecipes=dev.morphia.UpgradeToMorphia30
          mvn test-compile
