name: Test Morphia Upgrades

on:
  workflow_dispatch:
  schedule:
    - cron: @weekly

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with Tests
        run: |
          mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
            -Drewrite.recipeArtifactCoordinates=dev.morphia.morphia:rewrite:3.0.0-SNAPSHOT \
            -Drewrite.activeRecipes=dev.morphia.UpgradeToMorphia30
          mvn -e -U verify